- id: Lake_Hassio_Rebooted
  alias: Reboot notification
  description: Notify when system rebooted
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Lake House Hassio Rebooted
    service: notify.lakehouse_hassio
- id: lakehouse_smoke
  alias: Smoke Detected
  description: ''
  trigger:
  - entity_id: sensor.smoke_status
    from: idle
    platform: state
    to: smoke
  condition: []
  action:
  - data:
      message: Smoke detected upstairs at Lake House!
    service: notify.lakehouse_hassio
- id: lakehouse_co
  alias: Carbon Monoxide Detected
  description: ''
  trigger:
  - entity_id: sensor.smoke_status
    from: idle
    platform: state
    to: co
  condition: []
  action:
  - data:
      message: Carbon Monoxide detected upstairs at Lake House!
    service: notify.lakehouse_hassio
- id: lakehouse_flood
  alias: Water detected in basement
  description: ''
  trigger:
  - entity_id: sensor.flood_status
    from: dry
    platform: state
    to: flood
  condition: []
  action:
  - data:
      message: Lakehouse- Water detected on basement floor
    service: notify.lakehouse_hassio
- id: '1588362768033'
  alias: Propane Reading Old
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      node_id: 19
      parameter: 11
      size: 1
      value: 100
    service: zwave.set_config_parameter
  - device_id: 1376937c0ea042f5be036cefd84348bd
    domain: switch
    entity_id: switch.mimolite_switch
    type: turn_on
  - data_template:
      node_id: 19
      value_id: '72057594361692194'
    service: zwave.refresh_node_value
  - delay: '2'
  - data_template:
      node_id: 19
      value_id: '72057594361692194'
    service: zwave.refresh_node_value
  - data:
      name: Joe
    service: python_script.hello_world
- id: '1588367245709'
  alias: ZWRefreshTest
  description: ''
  trigger: []
  condition: []
  action:
  - service: zwave.refresh_node_value
    data_template:
      node_id: 19
      value_id: '72057594361692194'
- id: '1588717297110'
  alias: Read Propane Level
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_propane_level
    event_data:
      state: 'on'
- id: '1589322076669'
  alias: Daily Propane Level Update
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - event: update_propane_level
    event_data:
      state: 'on'
  mode: single
- id: archive_logs
  alias: Create an archive tar file of current logs
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - event: create_archive
    event_data:
      state: 'on'
- id: joe_left_home
  alias: Joe Left Home
  description: ''
  trigger:
  - entity_id: person.joe_thomas
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Joe Left Home
    service: notify.lakehouse_hassio
- id: jamie_left_home
  alias: Jamie Left Home
  description: ''
  trigger:
  - entity_id: person.jamie_thomas
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      message: Jamie Left Home
    service: notify.lakehouse_hassio
- id: joe_arrived_home
  alias: Joe Arrived Home
  description: ''
  trigger:
  - entity_id: person.joe_thomas
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Joe Arrived Home
    service: notify.lakehouse_hassio
- id: jamie_arrived_home
  alias: Jamie Arrived Home
  description: ''
  trigger:
  - entity_id: person.jamie_thomas
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - data:
      message: Jamie Arrived Home
    service: notify.lakehouse_hassio
- id: '1590326915142'
  alias: Front Door Event Test
  description: ''
  trigger:
  - entity_id: sensor.front_door_alarm_level
    platform: state
  condition: []
  action:
  - data:
      message: Front Door Event
    service: notify.lakehouse_hassio
- id: set_zwave_device_params
  alias: Set ZWave Device Params
  description: ''
  trigger: []
  condition: []
  action:
  - event: set_zwave_device_params
    event_data:
      state: 'on'
- id: front_door_opened
  alias: Front Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.joe_thomas
      state: not_home
    - condition: state
      entity_id: person.jamie_thomas
      state: not_home
  action:
  - data:
      message: Lakehouse Front Door Opened
    service: notify.lakehouse_hassio
- id: garage_door_opened
  alias: Garage Door Opened
  description: ''
  trigger:
  - entity_id: sensor.garage_door_access_control
    from: '23'
    platform: state
    to: '22'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.joe_thomas
      state: not_home
    - condition: state
      entity_id: person.jamie_thomas
      state: not_home
  action:
  - data:
      message: Lakehouse Garage Door Opened
    service: notify.lakehouse_hassio
- id: 34dt_disconnected
  alias: Check Goldens Bridge Disconnected
  description: ''
  trigger:
  - entity_id: sensor.34dt_hassio
    from: Up
    platform: state
    to: Down
  condition: []
  action:
  - data:
      message: Goldens Bridge had been reachable but is now not
    service: notify.lakehouse_hassio
  mode: single
- id: 34dt_reconnected
  alias: Check Goldens Reconnected
  description: ''
  trigger:
  - entity_id: sensor.34dt_hassio
    from: Down
    platform: state
    to: Up
  condition: []
  action:
  - data:
      message: Goldens Bridge is now reachable
    service: notify.lakehouse_hassio
  mode: single
- id: '1600695831917'
  alias: Turn Track Lights On Full
  description: ''
  trigger: []
  condition: []
  action:
  - brightness_pct: 100
    device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_on
  mode: single
- id: '1600695920076'
  alias: Turn On Movie Lighting
  description: ''
  trigger: []
  condition: []
  action:
  - brightness_pct: 1
    device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_on
  mode: single
- id: '1600696061493'
  alias: Turn Off Track Lights
  description: ''
  trigger: []
  condition: []
  action:
  - device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_off
  mode: single
- id: '1600696163642'
  alias: Turn Off Track Lights at Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_off
  mode: single
