- id: '1600695831917'
  alias: Turn Track Lights On Full
  description: ''
  trigger: []
  condition: []
  action:
  - brightness_pct: 100
    device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_on
  mode: single
- id: '1600695920076'
  alias: Turn On Movie Lighting
  description: ''
  trigger: []
  condition: []
  action:
  - brightness_pct: 1
    device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_on
  mode: single
- id: '1600696061493'
  alias: Turn Off Track Lights
  description: ''
  trigger: []
  condition: []
  action:
  - device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_off
  mode: single
- id: '1600696163642'
  alias: Turn Off Track Lights at Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: 165e787014f64dc09c4c906cbe7e227a
    domain: light
    entity_id: light.track_light_dimmer
    type: turn_off
  mode: single
- id: set_joe_home_state
  alias: Set Joe Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: home
- id: set_joe_not_home_state
  alias: Set Joe Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: joe
      state: not_home
- id: set_jamie_home_state
  alias: Set Jamie Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: home
- id: set_jamie_not_home_state
  alias: Set Jamie Not Home State
  description: ''
  trigger: []
  condition: []
  action:
  - event: update_home_state
    event_data:
      person: jamie
      state: not_home
- id: '1657994392567'
  alias: TV On
  description: ''
  trigger: []
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.tv
      - switch.home_theater
  mode: single
- id: '1657994761588'
  alias: TV Off
  description: ''
  trigger: []
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.tv
      - switch.home_theater
  mode: single
- id: set_trusted_home
  alias: Set Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe_thomas
  - platform: state
    entity_id: person.jamie_thomas
  - platform: time
    at: 07:00:00
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ states(''person.joe_thomas'').lower()  == ''home'' or states(''person.jamie_thomas'').lower()
        == ''home'' }}'
    - condition: time
      after: 07:00:00
      before: 09:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: true
  mode: single
- id: set_not_trusted_home
  alias: Set Not Trusted Home
  description: ''
  trigger:
  - platform: state
    entity_id: person.joe_thomas
  - platform: state
    entity_id: person.jamie_thomas
  - platform: time
    at: 09:00:00
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states(''person.joe_thomas'').lower()  == ''home'' or
          states(''person.jamie_thomas'').lower() == ''home'' }}'
      - condition: time
        after: 07:00:00
        before: 09:00:00
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: var.set
    data:
      entity_id:
      - var.trusted_home
      value: false
