- platform: command_line
  name: 34DT Hassio
  command: /usr/bin/nc -z -w7 deerjoe.groks-the.info 8123 && echo Up || echo Down

- platform: template
  sensors:
    #
    # Smoke and Carbon Monixide Detectors
    #
    smoke_status:
      friendly_name: "Smoke Status"
      value_template: >-
        {% if is_state("binary_sensor.smoke_alarm_smoke_detected", "on") %}
          smoke
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.smoke_alarm_smoke_detected", "on") %}
          mdi:fire
        {% else %}
          mdi:smoke-detector
        {% endif %}
    front_door_status:
      friendly_name: "Front_Door Status"
      value_template: >-
        {% if is_state("binary_sensor.front_door_sensor", "off")%}
          closed
        {% else %}
          open
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.front_door_sensor", "off")%}
          mdi:door
        {% else %}
          mdi:door-open
        {% endif %}
    garage_status:
      friendly_name: "Garage Status"
      value_template: >-
        {% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_access_control_window_door_is_open", "off")%}
          closed
        {% else %}
          open
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_access_control_window_door_is_open", "off")%}
          mdi:garage-variant
        {% else %}
          mdi:garage-open-variant
        {% endif %}
    flood_status:
      friendly_name: "Flood Status"
      value_template: >-
        {% if is_state("binary_sensor.flood_sensor_water_leak_state", "on")%}
          flood
        {% else %}
          dry
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.flood_sensor_water_leak_state", "on")%}
          mdi:waves
        {% else %}
          mdi:water-off
        {% endif %}


